### ISSUE TITLE
Subtlety - Clean Up HTML

### ISSUE THREAD

**Issue by davecastlevania** [Kurai-Shenteimo/prj-rev-bwfs-dasmoto#2]
https://github.com/Kurai-Shenteimo/prj-rev-bwfs-dasmoto/blob/master/DasmotoProject/index.html#L1-L43

You should consider cleaning up your code using a tool like [DirtyMarkup](https://dirtymarkup.com/). It's important for you to keep your code clean because it makes it easier for other developers to read and it's a good habit to have. You can read more [here](https://google.github.io/styleguide/htmlcssguide.html) and [here](https://www.smashingmagazine.com/2008/11/12-principles-for-keeping-your-code-clean/).

**Comment by Kurai-Shenteimo** [comment]
I will take the information to heart. On a side note, is there a 'clean' way to use comments. I put my code into 'DirtyMarkup' to compare and I had noticed all my comments were on the same line as the divs, or is that the clean way?
