### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by davecastlevania** [Kurai-Shenteimo/prj-rev-bwfs-dasmoto#5]
Great job with this project, it looks like you got the design down. I like how you were able to keep the CSS clean and it really shows that you are starting to understand this project really well. There were a couple of subtle changes that I would recommend, nothing major. Just good habits to have. If you want to really challenge yourself with this project I would come back to it once you learn more about responsive design/media queries and try making a mobile version of this site. Once again, excellent work!

I know Atom is a bit tricky to get used to so here are tips -http://www.creativebloq.com/advice/10-power-tips-for-atom-users

**Comment by Kurai-Shenteimo** [comment]
Thank you for the input, it means a lot to me and now I know what I need to work on.
